# A simple store configuration: we use one database for everything
# This is equivalent to the old way of configuring the store for tests
# by just setting the environment variable THEGRAPH_STORE_POSTGRES_DIESEL_URL

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
pool_size = 10

[deployment]
[[deployment.rule]]
store = "primary"
indexers = ["default"]

[chains]
ingestor = "default"

[chains.matic]
shard = "primary"

# archive node test: 
#   curl https://polygon.blockpi.network/v1/rpc/public -X POST -H "Content-Type: application/json" --data '{"method":"eth_getBalance","params":["0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270", "0x55"],"id":1,"jsonrpc":"2.0"}'
provider = [
  { label = "ankr", url = "https://rpc.ankr.com/polygon", features = ["archive"] },
  { label = "finality", url = "https://polygon.api.onfinality.io/public", features = ["archive"] },
  { label = "tenderly", url = "https://gateway.tenderly.co/public/polygon", features = ["archive"] },
  { label = "meowrpc", url = "https://polygon.meowrpc.com", features = [] },
  { label = "dprc", url = "https://polygon.drpc.org", features = ["archive"] },
  { label = "pokt", url = "https://polygon-pokt.nodies.app", features = [] },
  { label = "polygon", url = "https://polygon-rpc.com", features = ["archive"] },
  { label = "blockpi", url = "https://polygon.blockpi.network/v1/rpc/public", features = [] }
]
